// Curated starting points, not an exhaustive directory of food ordering sites.
// Short, ambiguous names use qualified aliases to avoid hiding ordinary words.
globalThis.HungerCatalog = [
  { id: "delivery", name: "Food delivery", description: "Delivery apps and ordering platforms", services: [
    ["DoorDash", ["doordash.com", "drd.sh"], ["DoorDash", "Door Dash", "DashPass"]],
    ["Uber Eats", ["ubereats.com", "ubereats.co.jp"], ["Uber Eats", "UberEats"]],
    ["Grubhub", ["grubhub.com", "grubhub.app.link"], ["Grubhub", "Grub Hub"]],
    ["Seamless", ["seamless.com"], ["Seamless delivery", "Seamless food"]],
    ["Postmates", ["postmates.com"], ["Postmates"]],
    ["Caviar", ["trycaviar.com"], ["Caviar delivery", "Caviar food delivery"]],
    ["Deliveroo", ["deliveroo.com", "deliveroo.co.uk", "deliveroo.fr", "deliveroo.it", "deliveroo.ae", "deliveroo.com.au", "deliveroo.com.sg", "deliveroo.ie", "deliveroo.com.hk", "deliveroo.be"], ["Deliveroo"]],
    ["Just Eat", ["just-eat.com", "just-eat.co.uk", "just-eat.ie", "just-eat.fr", "just-eat.es", "just-eat.it", "just-eat.dk", "just-eat.ch"], ["Just Eat", "JustEat"]],
    ["SkipTheDishes", ["skipthedishes.com"], ["SkipTheDishes", "Skip the Dishes"]],
    ["Wolt", ["wolt.com"], ["Wolt"]],
    ["foodpanda", ["foodpanda.com", "foodpanda.pk", "foodpanda.sg", "foodpanda.hk", "foodpanda.ph", "foodpanda.com.bd", "foodpanda.com.tw"], ["foodpanda", "food panda"]],
    ["Foodhub", ["foodhub.com", "foodhub.co.uk"], ["Foodhub"]],
    ["Swiggy", ["swiggy.com"], ["Swiggy"]],
    ["Zomato", ["zomato.com"], ["Zomato"]],
    ["Glovo", ["glovoapp.com"], ["Glovo"]],
    ["Rappi", ["rappi.com", "rappi.com.mx", "rappi.com.br", "rappi.com.co"], ["Rappi"]],
    ["iFood", ["ifood.com.br"], ["iFood"]],
    ["Talabat", ["talabat.com"], ["Talabat"]],
    ["HungerStation", ["hungerstation.com"], ["HungerStation"]],
    ["Menulog", ["menulog.com.au", "menulog.co.nz"], ["Menulog"]],
    ["Lieferando", ["lieferando.de", "lieferando.at"], ["Lieferando"]],
    ["Thuisbezorgd", ["thuisbezorgd.nl"], ["Thuisbezorgd"]],
    ["Takeaway.com", ["takeaway.com"], ["Takeaway.com"]],
    ["ChowNow", ["chownow.com"], ["ChowNow", "Chow Now"]],
    ["Toast Takeout", ["toasttab.com"], ["Toast Takeout", "Toast Local", "toasttab"]],
    ["Slice", ["slicelife.com"], ["Slice pizza", "slicelife"]],
    ["Beyond Menu", ["beyondmenu.com"], ["BeyondMenu", "Beyond Menu"]],
    ["MenuPages", ["menupages.com"], ["MenuPages"]],
    ["EatStreet", ["eatstreet.com"], ["EatStreet"]],
    ["Delivery.com", ["delivery.com"], ["delivery.com"]],
    ["ezCater", ["ezcater.com"], ["ezCater"]],
    ["Fantuan", ["fantuan.ca", "fantuanorder.com"], ["Fantuan"]],
    ["HungryPanda", ["hungrypanda.co"], ["HungryPanda"]]
  ] },
  { id: "restaurants", name: "Restaurant ordering", description: "Popular chains and their websites", services: [
    ["Domino’s", ["dominos.com", "dominos.co.uk", "dominos.ca", "dominos.com.au"], ["Domino's", "Domino’s", "Dominos pizza"]],
    ["Pizza Hut", ["pizzahut.com", "pizzahut.co.uk", "pizzahut.ca"], ["Pizza Hut", "PizzaHut"]],
    ["Papa Johns", ["papajohns.com", "papajohns.co.uk"], ["Papa Johns", "Papa John's", "Papa John’s"]],
    ["Little Caesars", ["littlecaesars.com"], ["Little Caesars", "Little Caesar's"]],
    ["McDonald’s", ["mcdonalds.com"], ["McDonald's", "McDonald’s", "McDonalds", "McDelivery"]],
    ["Burger King", ["bk.com", "burgerking.com", "burgerking.co.uk"], ["Burger King"]],
    ["Wendy’s", ["wendys.com"], ["Wendy's", "Wendy’s"]],
    ["Taco Bell", ["tacobell.com"], ["Taco Bell"]],
    ["Chipotle", ["chipotle.com"], ["Chipotle Mexican Grill", "order Chipotle"]],
    ["Chick-fil-A", ["chick-fil-a.com"], ["Chick-fil-A", "Chick fil A"]],
    ["KFC", ["kfc.com", "kfc.co.uk"], ["KFC", "Kentucky Fried Chicken"]],
    ["Popeyes", ["popeyes.com"], ["Popeyes"]],
    ["Subway", ["subway.com"], ["Subway sandwiches", "Subway delivery"]],
    ["Panera Bread", ["panerabread.com"], ["Panera", "Panera Bread"]],
    ["Jimmy John’s", ["jimmyjohns.com"], ["Jimmy John's", "Jimmy John’s", "Jimmy Johns"]],
    ["Jersey Mike’s", ["jerseymikes.com"], ["Jersey Mike's", "Jersey Mike’s"]],
    ["Wingstop", ["wingstop.com"], ["Wingstop"]],
    ["Buffalo Wild Wings", ["buffalowildwings.com"], ["Buffalo Wild Wings"]],
    ["Panda Express", ["pandaexpress.com"], ["Panda Express"]],
    ["Shake Shack", ["shakeshack.com"], ["Shake Shack"]],
    ["Five Guys", ["fiveguys.com"], ["Five Guys"]],
    ["Sonic Drive-In", ["sonicdrivein.com"], ["Sonic Drive-In", "Sonic Drive In"]],
    ["Starbucks", ["starbucks.com"], ["Starbucks"]],
    ["Dunkin’", ["dunkindonuts.com"], ["Dunkin", "Dunkin'", "Dunkin’"]]
  ] },
  { id: "groceries", name: "Groceries & convenience", description: "Grocery delivery and quick commerce", services: [
    ["Instacart", ["instacart.com", "instacart.ca"], ["Instacart"]],
    ["Shipt", ["shipt.com"], ["Shipt"]],
    ["Gopuff", ["gopuff.com"], ["Gopuff", "Go Puff"]],
    ["FreshDirect", ["freshdirect.com"], ["FreshDirect", "Fresh Direct"]],
    ["Weee!", ["sayweee.com"], ["sayweee", "Weee!"]],
    ["Misfits Market", ["misfitsmarket.com"], ["Misfits Market"]],
    ["Thrive Market", ["thrivemarket.com"], ["Thrive Market"]],
    ["Ocado", ["ocado.com"], ["Ocado"]],
    ["Blinkit", ["blinkit.com"], ["Blinkit"]],
    ["Zepto", ["zeptonow.com"], ["Zepto delivery", "Zepto groceries"]]
  ] },
  { id: "mealKits", name: "Meal kits & prepared meals", description: "Subscriptions and ready-made meals", services: [
    ["HelloFresh", ["hellofresh.com", "hellofresh.co.uk", "hellofresh.ca", "hellofresh.com.au"], ["HelloFresh", "Hello Fresh"]],
    ["Blue Apron", ["blueapron.com"], ["Blue Apron"]],
    ["Home Chef", ["homechef.com"], ["Home Chef"]],
    ["Factor", ["factor75.com", "factormeals.com"], ["Factor meals", "Factor75"]],
    ["CookUnity", ["cookunity.com"], ["CookUnity"]],
    ["Daily Harvest", ["daily-harvest.com", "dailyharvest.com"], ["Daily Harvest"]],
    ["EveryPlate", ["everyplate.com"], ["EveryPlate"]],
    ["Dinnerly", ["dinnerly.com"], ["Dinnerly"]],
    ["Sunbasket", ["sunbasket.com"], ["Sunbasket"]],
    ["Purple Carrot", ["purplecarrot.com"], ["Purple Carrot"]]
  ] }
];
